### ISSUE TITLE
Donor's app flow

### ISSUE THREAD

**Issue by abdulmuq** [donorcall01/DonorOnCall_Client#4]
Home - https://marvelapp.com/3ieibd6#9332536
Menu - https://marvelapp.com/3ieibd6#9332575

Donor will be notified via e-mail and sms when a request for blood arises. 
He can choose to accept the request - https://marvelapp.com/3ieibd6#9332537
Or view more information/contact the recipient - https://marvelapp.com/3ieibd6#9332540, https://marvelapp.com/3ieibd6#9332542
Donor can also request for blood in the menu

**Comment by prashanth9962** [comment]
will be using this for understanding app flow.closing this  as this not a issue
